### PR TITLE
(#1) Import the MSI template

### LINKED ISSUE #1: Move source files for msi.template package into this repository
The package can be found here:

https://community.chocolatey.org/packages/msi.template

Once complete, we can remove the source files from this repository:

https://github.com/ferventcoder/chocolatey-packages

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
1. Imports the MSI template from @ferventcoder's repository.
1. Updates the metadata of the template to reflect the new repository and
community maintenance. Fixes the BOM on nuspec and template nuspec.

I'm still working on other improvements to this template, if desired, those could be put in a follow along PR.

Fixes #1

### CODE REVIEW

**Comment by gep13** [comment]
I think a follow up PR, after transferring into the repository, makes sense.

**Comment by TheCakeIsNaOH** [comment]
Feel free to bring in anyone else you think you review this.

**Comment by gep13** [comment]
I know that @AdmiringWorm was in the process of moving his template into here as well, and he has some ideas around folder structure. So let's wait for him to respond here as well.

At a minimum I know he was suggesting creating a top level tests folder for allowing creation of scripts to help verify functionality of templates.

**Comment by AdmiringWorm** [comment]
The top-level directories that I was thinking of is an `src` directory where the source of the templates are located, and a `test` directory where the tests for the different pester tests for the templates are located.

I opened #8 where you can see this structure being used (was supposed to open it yesterday, but never got around to it).

**Comment by AdmiringWorm** [comment]
> Updates the metadata of the template to reflect the new repository and
community maintenance. Fixes the BOM on nuspec and template nuspec.

@TheCakeIsNaOH I am curious about this. Was this added or removed from the template nuspec?
I found that if it is removed from the template nuspec, then Chocolatey may not generate the file correctly if it contains non-ascii characters.

**Comment by TheCakeIsNaOH** [comment]
> The top-level directories that I was thinking of is an src directory where the source of the templates are located, and a test directory where the tests for the different pester tests for the templates are located.

Sounds good, I'll update this PR when I have a bit of time.

> Was this added or removed from the template nuspec?

Removed from both nuspecs.

> I found that if it is removed from the template nuspec, then Chocolatey may not generate the file correctly if it contains non-ascii characters.

Oh interesting, let's get this either fixed or documented. (Unless it already is documented and I had missed it)

**Comment by TheCakeIsNaOH** [comment]
I've updated the PR, rebased on master. The BOM is now included in the `msi.nuspec.template` as recommended by @AdmiringWorm 

I've also added a fix for the tests, so the installation portion will work with multiple packages.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
Thanks for getting this moved over!

**Pull request merged**
